version: "2"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: saphi123
      INFLUXDB_DB: mldcs